---
title: "DHW CRW data"
format: html
editor: visual
---

```{r}
library(httr) #for downloads
library(here) #for project folder structure
library(tidyverse)
library(pbapply) #for progress bars
library(raster) #to load .nc files
library(lubridate) #fast date change function
library(sf) # mapping
library(ggspatial) # mapping
library(viridis) #plots
library(patchwork) #plots
library(ncdf4) # read files
library(patchwork)
library(zoo)
```

s

```{r}
source(here("dhw/scripts/Andi_DHW_functions.R"))
```

Get MMM from Dixon et al.

```{r}
 # url_climatology = "https://www.star.nesdis.noaa.gov/pub/sod/mecb/crw/data/5km/v3.1_op/climatology/nc/ct5km_climatology_v3.1.nc"
 # 
 # httr::GET(url_climatology,
 #             httr::write_disk(here("dhw/data/crw_mmm.nc"),
 #                              overwrite = T),
 #             httr::add_headers('Accept-Encoding' = 'gzip, deflate'),
 #             httr::progress("down"),
 #             httr::timeout(600))

```

Define Moorea ROI

```{r}
moorea_lat = -17.536273
moorea_lon = -149.832730

moorea_box = bounding_box(moorea_lat, moorea_lon, 15, 15)
```

Get MMM and subset

```{r}
crw_mmm <- raster::brick(here("dhw/data/crw_mmm.nc"), varname = "sst_clim_mmm") %>% 
  subset_ncdf(lat_min = moorea_box$lat_min,
              lat_max = moorea_box$lat_max,
              lon_min = moorea_box$lon_min,
              lon_max = moorea_box$lon_max)
```

Map Moorea

```{r}
map_FrenchPolynesia <- st_read(dsn = here("dhw/data/maps/polynesia_map/PYF_adm0.shp")) %>%
  st_as_sf()
```

Area to be downloaded. Add MMM as overlay

```{r}
map_moorea <- ggplot() +
  geom_raster(data = crw_mmm, aes(x = lon, y = lat, fill = mmm)) +
  geom_sf(data = map_FrenchPolynesia,
          fill = "antiquewhite",
          col = "black")+
  coord_sf(xlim = c(moorea_box$lon_min, moorea_box$lon_max),
           ylim = c(moorea_box$lat_min, moorea_box$lat_max))+
  labs(x=NULL, y = NULL, title = "Moorea")+
  scale_fill_viridis(name = "MMM")+
  theme_minimal()

map_moorea
```

Get DHW Data

```{r}
# download_all(lat1 = moorea_box$lat_min,
#               lat2 = moorea_box$lat_max,
#               lon1 = moorea_box$lon_min,
#               lon2 = moorea_box$lon_max,
#               day1 = "2019-01-01",
#               day2 = "2019-12-31",
#               parameter = "CRW_DHW",
#               folder = here("dhw/data/sst/crw"))

```

```{r}
dat_moorea_crw_dhw <- read_nc(here("dhw/data/sst/crw"),
                      varname = "CRW_DHW",
                      values_to = "dhw")
```

Get max DHW

```{r}
dat_moorea_crw_dhw %>% 
  filter(lat == -17.525, lon == -149.825)
```

```{r}
dat_moorea_crw_dhwS <- dat_moorea_crw_dhw %>% 
  filter(!is.na(dhw)) %>% 
  group_by(lat, lon) %>%  
  summarise(max_dhw = max(dhw, na.rm = T)) %>% 
  ungroup()
```

Plot

```{r}
map_moorea_max_dhw <- ggplot() +
  geom_raster(data = dat_moorea_crw_dhwS, aes(x = lon, y = lat, fill = max_dhw)) +
  geom_sf(data = map_FrenchPolynesia,
          fill = "antiquewhite",
          col = "black")+
  coord_sf(xlim = c(moorea_box$lon_min, moorea_box$lon_max),
           ylim = c(moorea_box$lat_min, moorea_box$lat_max))+
  labs(x=NULL, y = NULL)+
  scale_fill_viridis(name = "max. DHW")+
  theme_minimal()

map_moorea_max_dhw

```

```{r}
ggsave(filename = "map_moorea_max_dhw.png",
       plot = map_moorea_max_dhw, 
       path = here("dhw/plots"),
       width = 30/3, height = 25/3, units = "cm")
```

```{r}

dat_moorea_crw_dhw %>% 
  ggplot(aes(x = date, y = dhw))+
  geom_line()+
  facet_grid(-lat~-lon)

```

Add max dhw to site coordinates

```{r}
dat_sites <- read.csv(here("dhw/data/dat_mm_site_coordinates.csv"))
```

```{r}
dat_sites <- dat_sites %>% 
  rowwise() %>% 
  mutate(dhw_max = find_closest_maxdhw(data = dat_moorea_crw_dhwS, lat = lat, lon = lon)) %>% 
  ungroup()
```

```{r}
write.csv(dat_sites, file = here("dhw/data/dat_sites_maxdhw_crw.csv"),row.names = F)
```
